language: java
jdk: oraclejdk8
#services: rabbitmq
services: docker
env: SPRING_PROFILES_ACTIVE=default
before_install: docker-compose up -d
script: ./gradlew build
after_script:
- docker-compose kill
- gradle dependencyUpdates -Drevision=release
cache.directories:
- /var/lib/docker
- $HOME/.gradle
- $HOME/.m2
- .gradle
- gradle
notifications.on_failure: never
